edited line 20
edited line 20: from changed num = random.randint(1, lgth_file) to num = random.randint(0, lgth_file-1) because I was occasionally getting and IndexError (chunk = cont[num] # extract a line from the lines of the file
IndexError: list index out of range)